### ISSUE TITLE
Lack Controllers\S3ProxyController 

### ISSUE THREAD

**Issue by silentnull** [michaeldimoudis/aspnetcore-22-webapi-lambda-serverless#3]
Hi,

I see you solution of use custom .NET 2.2 Runtime in lamdba.
In Readme is that exists S3ProxyContoller ? Where is souce of this file ?

**Comment by michaeldimoudis** [comment]
Hi, that's from the AWS template in Visual Studio. Install AWS tools, and you can File -> New Project -> AWS to see a list of starter projects. I stripped out most of the unnecessary code to focus on just the asp.net core app.
